### ISSUE TITLE
A Wire.requestFrom() should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [TS22082/IOT_Telemetry#1]
In the file "IOT_Telemetry/UnoSensor/UnoSensor.ino" a Wire.requestFrom() is followed by Wire.endTransmission(), but the Wire.endTransmission() should only be used when writing data.
Explanation: [Common-mistakes#2](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#2)

**Comment by TS22082** [comment]
Thanks for catching that @Koepel. Fixed and committed.
